Alert-message: "Alert: {message}"

No-Permission: "You do not have permission to use this command"
Incorrect-Usage: "Usage: /alert <message>"

Sound: "minecraft:block.note_block.bell" # Leave empty to disable
Pitch: 0.0f
ActionBar: true # While true the message will also appear on the player's actionbar

Permission: "VelocityAlert.use"
